services:
  backend:
    build: ./backend
    container_name: euklydia-backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./euklydia-frontend
      args:
        - REACT_APP_API_URL=https://euklydia-academy-backend-488435447606.europe-west1.run.app
    container_name: euklydia-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend