"""add rich content fields to modules

Revision ID: 14aae6f2d082
Revises: d1b5b84bea5b
Create Date: 2026-03-25 17:52:50.195521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14aae6f2d082'
down_revision: Union[str, Sequence[str], None] = 'd1b5b84bea5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('comparison_tables_en', sa.JSON(), nullable=True))
    op.add_column('modules', sa.Column('comparison_tables_fr', sa.JSON(), nullable=True))
    op.add_column('modules', sa.Column('quiz_questions_en', sa.JSON(), nullable=True))
    op.add_column('modules', sa.Column('quiz_questions_fr', sa.JSON(), nullable=True))
    op.add_column('modules', sa.Column('prompt_examples_en', sa.JSON(), nullable=True))
    op.add_column('modules', sa.Column('prompt_examples_fr', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'prompt_examples_fr')
    op.drop_column('modules', 'prompt_examples_en')
    op.drop_column('modules', 'quiz_questions_fr')
    op.drop_column('modules', 'quiz_questions_en')
    op.drop_column('modules', 'comparison_tables_fr')
    op.drop_column('modules', 'comparison_tables_en')
    # ### end Alembic commands ###
