"""add modules and module_skills tables

Revision ID: 3d6e80962902
Revises: e05146dc4ca0
Create Date: 2026-03-15 21:20:05.805171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6e80962902'
down_revision: Union[str, Sequence[str], None] = 'e05146dc4ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learning_objective', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'skill_id', name='uq_module_skill')
    )
    op.create_index(op.f('ix_module_skills_module_id'), 'module_skills', ['module_id'], unique=False)
    op.create_index(op.f('ix_module_skills_skill_id'), 'module_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_module_skills_skill_id'), table_name='module_skills')
    op.drop_index(op.f('ix_module_skills_module_id'), table_name='module_skills')
    op.drop_table('module_skills')
    op.drop_table('modules')
    # ### end Alembic commands ###
