"""add section content to modules

Revision ID: 9aafec789d9c
Revises: 14aae6f2d082
Create Date: 2026-03-25 21:17:10.920826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aafec789d9c'
down_revision: Union[str, Sequence[str], None] = '14aae6f2d082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('section_content_en', sa.JSON(), nullable=True))
    op.add_column('modules', sa.Column('section_content_fr', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'section_content_fr')
    op.drop_column('modules', 'section_content_en')
    # ### end Alembic commands ###
