"""add_qcm_fields_to_questions

Revision ID: a8a4ebd3404b
Revises: bbc4423cfa3a
Create Date: 2026-04-06 22:26:02.784548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a4ebd3404b'
down_revision: Union[str, Sequence[str], None] = 'bbc4423cfa3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Étape 1 — ajouter les colonnes nullable=True
    op.add_column('questions', sa.Column('option_a', sa.String(300), nullable=True))
    op.add_column('questions', sa.Column('option_b', sa.String(300), nullable=True))
    op.add_column('questions', sa.Column('option_c', sa.String(300), nullable=True))
    op.add_column('questions', sa.Column('option_d', sa.String(300), nullable=True))
    op.add_column('questions', sa.Column('correct_answer', sa.String(1), nullable=True))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('order', sa.Integer(), nullable=True, server_default='1'))
    op.add_column('questions', sa.Column('role_id', sa.Integer(), sa.ForeignKey('career_paths.id'), nullable=True))

    # Étape 2 — vider les anciennes données
    op.execute("DELETE FROM user_responses")
    op.execute("DELETE FROM questions")

    # Étape 3 — passer les colonnes en NOT NULL
    op.alter_column('questions', 'option_a', nullable=False)
    op.alter_column('questions', 'option_b', nullable=False)
    op.alter_column('questions', 'option_c', nullable=False)
    op.alter_column('questions', 'option_d', nullable=False)
    op.alter_column('questions', 'correct_answer', nullable=False)
    op.alter_column('questions', 'order', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'order')
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'option_d')
    op.drop_column('questions', 'option_c')
    op.drop_column('questions', 'option_b')
    op.drop_column('questions', 'option_a')
    # ### end Alembic commands ###
