"""add practical_exercise to modules

Revision ID: bbc4423cfa3a
Revises: 9aafec789d9c
Create Date: 2026-03-26 13:08:30.338635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc4423cfa3a'
down_revision: Union[str, Sequence[str], None] = '9aafec789d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('practical_exercise_en', sa.JSON(), nullable=True))
    op.add_column('modules', sa.Column('practical_exercise_fr', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'practical_exercise_fr')
    op.drop_column('modules', 'practical_exercise_en')
    # ### end Alembic commands ###
