"""make skills global and add module display_order

Revision ID: bcd9a5cd7e0c
Revises: d461bc78cfdb
Create Date: 2026-03-16 13:58:58.980279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd9a5cd7e0c'
down_revision: Union[str, Sequence[str], None] = 'd461bc78cfdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('display_order', sa.Integer(), nullable=True))
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('skills', 'description',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'skills', ['name'])
    op.drop_constraint(op.f('skills_career_path_id_fkey'), 'skills', type_='foreignkey')
    op.drop_column('skills', 'career_path_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('career_path_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('skills_career_path_id_fkey'), 'skills', 'career_paths', ['career_path_id'], ['id'])
    op.drop_constraint(None, 'skills', type_='unique')
    op.alter_column('skills', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('skills', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('modules', 'display_order')
    # ### end Alembic commands ###
