"""add user_module_progress table

Revision ID: c088e3130e4f
Revises: bcd9a5cd7e0c
Create Date: 2026-03-16 23:29:48.464843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c088e3130e4f'
down_revision: Union[str, Sequence[str], None] = 'bcd9a5cd7e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_module_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_user_module_progress')
    )
    op.create_index(op.f('ix_user_module_progress_module_id'), 'user_module_progress', ['module_id'], unique=False)
    op.create_index(op.f('ix_user_module_progress_user_id'), 'user_module_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_module_progress_user_id'), table_name='user_module_progress')
    op.drop_index(op.f('ix_user_module_progress_module_id'), table_name='user_module_progress')
    op.drop_table('user_module_progress')
    # ### end Alembic commands ###
