"""add_progress_percent_to_user_module_progress

Revision ID: d1b5b84bea5b
Revises: ec9134015c6d
Create Date: 2026-03-25 00:45:24.606129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b5b84bea5b'
down_revision: Union[str, Sequence[str], None] = 'ec9134015c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_module_progress', sa.Column('progress_percent', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_module_progress', 'progress_percent')
    # ### end Alembic commands ###
