"""refactor_questions_qcm_and_skills_role

Revision ID: d407397affb4
Revises: a8a4ebd3404b
Create Date: 2026-04-06 22:31:31.348480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd407397affb4'
down_revision: Union[str, Sequence[str], None] = 'a8a4ebd3404b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('questions_role_id_fkey'), 'questions', type_='foreignkey')
    op.drop_column('questions', 'role_id')
    op.add_column('skills', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('skills_name_key'), 'skills', type_='unique')
    op.create_foreign_key(None, 'skills', 'career_paths', ['role_id'], ['id'])
    op.add_column('user_responses', sa.Column('selected_option', sa.String(length=1), nullable=False))
    op.add_column('user_responses', sa.Column('is_correct', sa.Boolean(), nullable=False))
    op.drop_column('user_responses', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_responses', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_responses', 'is_correct')
    op.drop_column('user_responses', 'selected_option')
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.create_unique_constraint(op.f('skills_name_key'), 'skills', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('skills', 'role_id')
    op.add_column('questions', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('questions_role_id_fkey'), 'questions', 'career_paths', ['role_id'], ['id'])
    # ### end Alembic commands ###
