"""add module learning fields

Revision ID: d461bc78cfdb
Revises: 3d6e80962902
Create Date: 2026-03-16 11:47:26.820481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd461bc78cfdb'
down_revision: Union[str, Sequence[str], None] = '3d6e80962902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('role', sa.String(length=100), nullable=True))
    op.add_column('modules', sa.Column('journey_stage', sa.String(length=50), nullable=True))
    op.add_column('modules', sa.Column('expected_outcome', sa.Text(), nullable=True))
    op.add_column('modules', sa.Column('key_concepts', sa.JSON(), nullable=True))
    op.add_column('modules', sa.Column('role_based_example', sa.Text(), nullable=True))
    op.add_column('modules', sa.Column('takeaway', sa.Text(), nullable=True))
    op.add_column('modules', sa.Column('action_point', sa.Text(), nullable=True))
    op.add_column('modules', sa.Column('practical_application', sa.Text(), nullable=True))
    op.add_column('modules', sa.Column('recommended_when', sa.Text(), nullable=True))
    op.add_column('modules', sa.Column('why_this_module', sa.Text(), nullable=True))
    op.add_column('modules', sa.Column('next_recommended_module', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'next_recommended_module')
    op.drop_column('modules', 'why_this_module')
    op.drop_column('modules', 'recommended_when')
    op.drop_column('modules', 'practical_application')
    op.drop_column('modules', 'action_point')
    op.drop_column('modules', 'takeaway')
    op.drop_column('modules', 'role_based_example')
    op.drop_column('modules', 'key_concepts')
    op.drop_column('modules', 'expected_outcome')
    op.drop_column('modules', 'journey_stage')
    op.drop_column('modules', 'role')
    # ### end Alembic commands ###
