"""add_adaptive_learning_engine_tables

Revision ID: dfec483c07e6
Revises: 6fea02fdf1ae
Create Date: 2026-04-10 10:04:29.522726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfec483c07e6'
down_revision: Union[str, Sequence[str], None] = '6fea02fdf1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title_fr', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_module_id'), 'units', ['module_id'], unique=False)
    op.create_table('learner_skill_mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('mastery_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('last_update_reason', sa.Text(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skill_mastery')
    )
    op.create_index(op.f('ix_learner_skill_mastery_skill_id'), 'learner_skill_mastery', ['skill_id'], unique=False)
    op.create_index(op.f('ix_learner_skill_mastery_user_id'), 'learner_skill_mastery', ['user_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_lesson_id', sa.Integer(), nullable=True),
    sa.Column('title_fr', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=True),
    sa.Column('video_script_fr', sa.Text(), nullable=True),
    sa.Column('video_script_en', sa.Text(), nullable=True),
    sa.Column('video_url_fr', sa.String(length=500), nullable=True),
    sa.Column('video_url_en', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_prerequisite_lesson_id'), 'lessons', ['prerequisite_lesson_id'], unique=False)
    op.create_index(op.f('ix_lessons_unit_id'), 'lessons', ['unit_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title_fr', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('content_fr', sa.JSON(), nullable=True),
    sa.Column('content_en', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_assessed', sa.Boolean(), nullable=False),
    sa.Column('has_hints', sa.Boolean(), nullable=False),
    sa.Column('hints_fr', sa.JSON(), nullable=True),
    sa.Column('hints_en', sa.JSON(), nullable=True),
    sa.Column('rubric_fr', sa.JSON(), nullable=True),
    sa.Column('rubric_en', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_lesson_id'), 'activities', ['lesson_id'], unique=False)
    op.create_table('learner_path_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_lesson_id', sa.Integer(), nullable=True),
    sa.Column('to_lesson_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('reason_fr', sa.Text(), nullable=True),
    sa.Column('reason_en', sa.Text(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('decision_source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_path_logs_user_id'), 'learner_path_logs', ['user_id'], unique=False)
    op.create_table('learner_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('time_on_task_seconds', sa.Integer(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('learner_response', sa.String(length=5000), nullable=True),
    sa.Column('llm_feedback_fr', sa.String(length=2000), nullable=True),
    sa.Column('llm_feedback_en', sa.String(length=2000), nullable=True),
    sa.Column('detailed_results', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_activity_logs_activity_id'), 'learner_activity_logs', ['activity_id'], unique=False)
    op.create_index(op.f('ix_learner_activity_logs_lesson_id'), 'learner_activity_logs', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_learner_activity_logs_user_id'), 'learner_activity_logs', ['user_id'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_learner_activity_logs_user_id'), table_name='learner_activity_logs')
    op.drop_index(op.f('ix_learner_activity_logs_lesson_id'), table_name='learner_activity_logs')
    op.drop_index(op.f('ix_learner_activity_logs_activity_id'), table_name='learner_activity_logs')
    op.drop_table('learner_activity_logs')
    op.drop_index(op.f('ix_learner_path_logs_user_id'), table_name='learner_path_logs')
    op.drop_table('learner_path_logs')
    op.drop_index(op.f('ix_activities_lesson_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_lessons_unit_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_prerequisite_lesson_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_learner_skill_mastery_user_id'), table_name='learner_skill_mastery')
    op.drop_index(op.f('ix_learner_skill_mastery_skill_id'), table_name='learner_skill_mastery')
    op.drop_table('learner_skill_mastery')
    op.drop_index(op.f('ix_units_module_id'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
