"""add password reset tokens

Revision ID: e05146dc4ca0
Revises: 9c7d6fb3c467
Create Date: 2026-03-09 20:46:23.501908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05146dc4ca0'
down_revision: Union[str, Sequence[str], None] = '9c7d6fb3c467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.drop_index(op.f('ix_diag_sessions_user_cp_created'), table_name='diagnostic_sessions')
    op.alter_column('user_responses', 'diagnostic_session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_user_skill_scores_diagnostic_session_id'), 'user_skill_scores', ['diagnostic_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_skill_scores_diagnostic_session_id'), table_name='user_skill_scores')
    op.alter_column('user_responses', 'diagnostic_session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_diag_sessions_user_cp_created'), 'diagnostic_sessions', ['user_id', 'career_path_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
